title : Jobert Leong
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
author : Jobert
description : The official site of Jobert Leong
